// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EEGProtos.proto

package org.tssg.sa;


public final class EEGProtos {
  private EEGProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EEGDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.tssg.sa.EEGData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string email = 1;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
     */
    org.tssg.sa.EEGProtos.EEGData.Timestamp getTimestamp();
    /**
     * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
     */
    org.tssg.sa.EEGProtos.EEGData.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
     */
    java.util.List<org.tssg.sa.EEGProtos.EEGData.DataType> getTypeList();
    /**
     * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
     */
    int getTypeCount();
    /**
     * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
     */
    org.tssg.sa.EEGProtos.EEGData.DataType getType(int index);
    /**
     * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
     */
    java.util.List<java.lang.Integer>
    getTypeValueList();
    /**
     * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
     */
    int getTypeValue(int index);

    /**
     * <code>repeated float value = 4;</code>
     */
    java.util.List<java.lang.Float> getValueList();
    /**
     * <code>repeated float value = 4;</code>
     */
    int getValueCount();
    /**
     * <code>repeated float value = 4;</code>
     */
    float getValue(int index);
  }
  /**
   * Protobuf type {@code org.tssg.sa.EEGData}
   */
  public  static final class EEGData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.tssg.sa.EEGData)
      EEGDataOrBuilder {
    // Use EEGData.newBuilder() to construct.
    private EEGData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EEGData() {
      email_ = "";
      type_ = java.util.Collections.emptyList();
      value_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EEGData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 18: {
              org.tssg.sa.EEGProtos.EEGData.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(org.tssg.sa.EEGProtos.EEGData.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                type_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              type_.add(rawValue);
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  type_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000004;
                }
                type_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
            case 37: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                value_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000008;
              }
              value_.add(input.readFloat());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                value_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                value_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          type_ = java.util.Collections.unmodifiableList(type_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          value_ = java.util.Collections.unmodifiableList(value_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tssg.sa.EEGProtos.EEGData.class, org.tssg.sa.EEGProtos.EEGData.Builder.class);
    }

    /**
     * Protobuf enum {@code org.tssg.sa.EEGData.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>EEG1 = 0;</code>
       */
      EEG1(0),
      /**
       * <code>EEG2 = 1;</code>
       */
      EEG2(1),
      /**
       * <code>EEG3 = 2;</code>
       */
      EEG3(2),
      /**
       * <code>EEG4 = 3;</code>
       */
      EEG4(3),
      /**
       * <code>AUX_LEFT = 4;</code>
       */
      AUX_LEFT(4),
      /**
       * <code>AUX_RIGHT = 5;</code>
       */
      AUX_RIGHT(5),
      /**
       * <code>ACCELX = 6;</code>
       */
      ACCELX(6),
      /**
       * <code>ACCELY = 7;</code>
       */
      ACCELY(7),
      /**
       * <code>ACCELZ = 8;</code>
       */
      ACCELZ(8),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>EEG1 = 0;</code>
       */
      public static final int EEG1_VALUE = 0;
      /**
       * <code>EEG2 = 1;</code>
       */
      public static final int EEG2_VALUE = 1;
      /**
       * <code>EEG3 = 2;</code>
       */
      public static final int EEG3_VALUE = 2;
      /**
       * <code>EEG4 = 3;</code>
       */
      public static final int EEG4_VALUE = 3;
      /**
       * <code>AUX_LEFT = 4;</code>
       */
      public static final int AUX_LEFT_VALUE = 4;
      /**
       * <code>AUX_RIGHT = 5;</code>
       */
      public static final int AUX_RIGHT_VALUE = 5;
      /**
       * <code>ACCELX = 6;</code>
       */
      public static final int ACCELX_VALUE = 6;
      /**
       * <code>ACCELY = 7;</code>
       */
      public static final int ACCELY_VALUE = 7;
      /**
       * <code>ACCELZ = 8;</code>
       */
      public static final int ACCELZ_VALUE = 8;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return EEG1;
          case 1: return EEG2;
          case 2: return EEG3;
          case 3: return EEG4;
          case 4: return AUX_LEFT;
          case 5: return AUX_RIGHT;
          case 6: return ACCELX;
          case 7: return ACCELY;
          case 8: return ACCELZ;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.tssg.sa.EEGProtos.EEGData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.tssg.sa.EEGData.DataType)
    }

    public interface TimestampOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.tssg.sa.EEGData.Timestamp)
        com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code org.tssg.sa.EEGData.Timestamp}
     */
    public  static final class Timestamp extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:org.tssg.sa.EEGData.Timestamp)
        TimestampOrBuilder {
      // Use Timestamp.newBuilder() to construct.
      private Timestamp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Timestamp() {
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Timestamp(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGData_Timestamp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGData_Timestamp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tssg.sa.EEGProtos.EEGData.Timestamp.class, org.tssg.sa.EEGProtos.EEGData.Timestamp.Builder.class);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.tssg.sa.EEGProtos.EEGData.Timestamp)) {
          return super.equals(obj);
        }
        org.tssg.sa.EEGProtos.EEGData.Timestamp other = (org.tssg.sa.EEGProtos.EEGData.Timestamp) obj;

        boolean result = true;
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.tssg.sa.EEGProtos.EEGData.Timestamp parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.tssg.sa.EEGProtos.EEGData.Timestamp parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.tssg.sa.EEGProtos.EEGData.Timestamp parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.tssg.sa.EEGProtos.EEGData.Timestamp parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.tssg.sa.EEGProtos.EEGData.Timestamp parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.tssg.sa.EEGProtos.EEGData.Timestamp parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.tssg.sa.EEGProtos.EEGData.Timestamp parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.tssg.sa.EEGProtos.EEGData.Timestamp parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.tssg.sa.EEGProtos.EEGData.Timestamp parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.tssg.sa.EEGProtos.EEGData.Timestamp parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.tssg.sa.EEGProtos.EEGData.Timestamp prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code org.tssg.sa.EEGData.Timestamp}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:org.tssg.sa.EEGData.Timestamp)
          org.tssg.sa.EEGProtos.EEGData.TimestampOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGData_Timestamp_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGData_Timestamp_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.tssg.sa.EEGProtos.EEGData.Timestamp.class, org.tssg.sa.EEGProtos.EEGData.Timestamp.Builder.class);
        }

        // Construct using org.tssg.sa.EEGProtos.EEGData.Timestamp.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGData_Timestamp_descriptor;
        }

        public org.tssg.sa.EEGProtos.EEGData.Timestamp getDefaultInstanceForType() {
          return org.tssg.sa.EEGProtos.EEGData.Timestamp.getDefaultInstance();
        }

        public org.tssg.sa.EEGProtos.EEGData.Timestamp build() {
          org.tssg.sa.EEGProtos.EEGData.Timestamp result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.tssg.sa.EEGProtos.EEGData.Timestamp buildPartial() {
          org.tssg.sa.EEGProtos.EEGData.Timestamp result = new org.tssg.sa.EEGProtos.EEGData.Timestamp(this);
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.tssg.sa.EEGProtos.EEGData.Timestamp) {
            return mergeFrom((org.tssg.sa.EEGProtos.EEGData.Timestamp)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.tssg.sa.EEGProtos.EEGData.Timestamp other) {
          if (other == org.tssg.sa.EEGProtos.EEGData.Timestamp.getDefaultInstance()) return this;
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.tssg.sa.EEGProtos.EEGData.Timestamp parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.tssg.sa.EEGProtos.EEGData.Timestamp) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:org.tssg.sa.EEGData.Timestamp)
      }

      // @@protoc_insertion_point(class_scope:org.tssg.sa.EEGData.Timestamp)
      private static final org.tssg.sa.EEGProtos.EEGData.Timestamp DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.tssg.sa.EEGProtos.EEGData.Timestamp();
      }

      public static org.tssg.sa.EEGProtos.EEGData.Timestamp getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Timestamp>
          PARSER = new com.google.protobuf.AbstractParser<Timestamp>() {
        public Timestamp parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Timestamp(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Timestamp> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Timestamp> getParserForType() {
        return PARSER;
      }

      public org.tssg.sa.EEGProtos.EEGData.Timestamp getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int EMAIL_FIELD_NUMBER = 1;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 1;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private org.tssg.sa.EEGProtos.EEGData.Timestamp timestamp_;
    /**
     * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
     */
    public org.tssg.sa.EEGProtos.EEGData.Timestamp getTimestamp() {
      return timestamp_ == null ? org.tssg.sa.EEGProtos.EEGData.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
     */
    public org.tssg.sa.EEGProtos.EEGData.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> type_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, org.tssg.sa.EEGProtos.EEGData.DataType> type_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, org.tssg.sa.EEGProtos.EEGData.DataType>() {
              public org.tssg.sa.EEGProtos.EEGData.DataType convert(java.lang.Integer from) {
                org.tssg.sa.EEGProtos.EEGData.DataType result = org.tssg.sa.EEGProtos.EEGData.DataType.valueOf(from);
                return result == null ? org.tssg.sa.EEGProtos.EEGData.DataType.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
     */
    public java.util.List<org.tssg.sa.EEGProtos.EEGData.DataType> getTypeList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, org.tssg.sa.EEGProtos.EEGData.DataType>(type_, type_converter_);
    }
    /**
     * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
     */
    public org.tssg.sa.EEGProtos.EEGData.DataType getType(int index) {
      return type_converter_.convert(type_.get(index));
    }
    /**
     * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
     */
    public java.util.List<java.lang.Integer>
    getTypeValueList() {
      return type_;
    }
    /**
     * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
     */
    public int getTypeValue(int index) {
      return type_.get(index);
    }
    private int typeMemoizedSerializedSize;

    public static final int VALUE_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Float> value_;
    /**
     * <code>repeated float value = 4;</code>
     */
    public java.util.List<java.lang.Float>
        getValueList() {
      return value_;
    }
    /**
     * <code>repeated float value = 4;</code>
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated float value = 4;</code>
     */
    public float getValue(int index) {
      return value_.get(index);
    }
    private int valueMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
      }
      if (timestamp_ != null) {
        output.writeMessage(2, getTimestamp());
      }
      if (getTypeList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(typeMemoizedSerializedSize);
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeEnumNoTag(type_.get(i));
      }
      if (getValueList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(valueMemoizedSerializedSize);
      }
      for (int i = 0; i < value_.size(); i++) {
        output.writeFloatNoTag(value_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTimestamp());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < type_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(type_.get(i));
        }
        size += dataSize;
        if (!getTypeList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }typeMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 4 * getValueList().size();
        size += dataSize;
        if (!getValueList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valueMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tssg.sa.EEGProtos.EEGData)) {
        return super.equals(obj);
      }
      org.tssg.sa.EEGProtos.EEGData other = (org.tssg.sa.EEGProtos.EEGData) obj;

      boolean result = true;
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && getTimestamp()
            .equals(other.getTimestamp());
      }
      result = result && type_.equals(other.type_);
      result = result && getValueList()
          .equals(other.getValueList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      if (getTypeCount() > 0) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_.hashCode();
      }
      if (getValueCount() > 0) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValueList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tssg.sa.EEGProtos.EEGData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tssg.sa.EEGProtos.EEGData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tssg.sa.EEGProtos.EEGData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tssg.sa.EEGProtos.EEGData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tssg.sa.EEGProtos.EEGData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tssg.sa.EEGProtos.EEGData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tssg.sa.EEGProtos.EEGData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tssg.sa.EEGProtos.EEGData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tssg.sa.EEGProtos.EEGData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tssg.sa.EEGProtos.EEGData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tssg.sa.EEGProtos.EEGData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.tssg.sa.EEGData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.tssg.sa.EEGData)
        org.tssg.sa.EEGProtos.EEGDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tssg.sa.EEGProtos.EEGData.class, org.tssg.sa.EEGProtos.EEGData.Builder.class);
      }

      // Construct using org.tssg.sa.EEGProtos.EEGData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        email_ = "";

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGData_descriptor;
      }

      public org.tssg.sa.EEGProtos.EEGData getDefaultInstanceForType() {
        return org.tssg.sa.EEGProtos.EEGData.getDefaultInstance();
      }

      public org.tssg.sa.EEGProtos.EEGData build() {
        org.tssg.sa.EEGProtos.EEGData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tssg.sa.EEGProtos.EEGData buildPartial() {
        org.tssg.sa.EEGProtos.EEGData result = new org.tssg.sa.EEGProtos.EEGData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.email_ = email_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          type_ = java.util.Collections.unmodifiableList(type_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          value_ = java.util.Collections.unmodifiableList(value_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tssg.sa.EEGProtos.EEGData) {
          return mergeFrom((org.tssg.sa.EEGProtos.EEGData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tssg.sa.EEGProtos.EEGData other) {
        if (other == org.tssg.sa.EEGProtos.EEGData.getDefaultInstance()) return this;
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tssg.sa.EEGProtos.EEGData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tssg.sa.EEGProtos.EEGData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 1;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 1;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 1;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 1;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private org.tssg.sa.EEGProtos.EEGData.Timestamp timestamp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.tssg.sa.EEGProtos.EEGData.Timestamp, org.tssg.sa.EEGProtos.EEGData.Timestamp.Builder, org.tssg.sa.EEGProtos.EEGData.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
       */
      public org.tssg.sa.EEGProtos.EEGData.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? org.tssg.sa.EEGProtos.EEGData.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
       */
      public Builder setTimestamp(org.tssg.sa.EEGProtos.EEGData.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
       */
      public Builder setTimestamp(
          org.tssg.sa.EEGProtos.EEGData.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
       */
      public Builder mergeTimestamp(org.tssg.sa.EEGProtos.EEGData.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              org.tssg.sa.EEGProtos.EEGData.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
       */
      public org.tssg.sa.EEGProtos.EEGData.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
       */
      public org.tssg.sa.EEGProtos.EEGData.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              org.tssg.sa.EEGProtos.EEGData.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.org.tssg.sa.EEGData.Timestamp timestamp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.tssg.sa.EEGProtos.EEGData.Timestamp, org.tssg.sa.EEGProtos.EEGData.Timestamp.Builder, org.tssg.sa.EEGProtos.EEGData.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.tssg.sa.EEGProtos.EEGData.Timestamp, org.tssg.sa.EEGProtos.EEGData.Timestamp.Builder, org.tssg.sa.EEGProtos.EEGData.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private java.util.List<java.lang.Integer> type_ =
        java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          type_ = new java.util.ArrayList<java.lang.Integer>(type_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public java.util.List<org.tssg.sa.EEGProtos.EEGData.DataType> getTypeList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, org.tssg.sa.EEGProtos.EEGData.DataType>(type_, type_converter_);
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public int getTypeCount() {
        return type_.size();
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public org.tssg.sa.EEGProtos.EEGData.DataType getType(int index) {
        return type_converter_.convert(type_.get(index));
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public Builder setType(
          int index, org.tssg.sa.EEGProtos.EEGData.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public Builder addType(org.tssg.sa.EEGProtos.EEGData.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public Builder addAllType(
          java.lang.Iterable<? extends org.tssg.sa.EEGProtos.EEGData.DataType> values) {
        ensureTypeIsMutable();
        for (org.tssg.sa.EEGProtos.EEGData.DataType value : values) {
          type_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public Builder clearType() {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public java.util.List<java.lang.Integer>
      getTypeValueList() {
        return java.util.Collections.unmodifiableList(type_);
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public int getTypeValue(int index) {
        return type_.get(index);
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public Builder setTypeValue(
          int index, int value) {
        ensureTypeIsMutable();
        type_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public Builder addTypeValue(int value) {
        ensureTypeIsMutable();
        type_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData.DataType type = 3;</code>
       */
      public Builder addAllTypeValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureTypeIsMutable();
        for (int value : values) {
          type_.add(value);
        }
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> value_ = java.util.Collections.emptyList();
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          value_ = new java.util.ArrayList<java.lang.Float>(value_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated float value = 4;</code>
       */
      public java.util.List<java.lang.Float>
          getValueList() {
        return java.util.Collections.unmodifiableList(value_);
      }
      /**
       * <code>repeated float value = 4;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated float value = 4;</code>
       */
      public float getValue(int index) {
        return value_.get(index);
      }
      /**
       * <code>repeated float value = 4;</code>
       */
      public Builder setValue(
          int index, float value) {
        ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float value = 4;</code>
       */
      public Builder addValue(float value) {
        ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float value = 4;</code>
       */
      public Builder addAllValue(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, value_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float value = 4;</code>
       */
      public Builder clearValue() {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.tssg.sa.EEGData)
    }

    // @@protoc_insertion_point(class_scope:org.tssg.sa.EEGData)
    private static final org.tssg.sa.EEGProtos.EEGData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tssg.sa.EEGProtos.EEGData();
    }

    public static org.tssg.sa.EEGProtos.EEGData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EEGData>
        PARSER = new com.google.protobuf.AbstractParser<EEGData>() {
      public EEGData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EEGData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EEGData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EEGData> getParserForType() {
      return PARSER;
    }

    public org.tssg.sa.EEGProtos.EEGData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EEGDataStreamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.tssg.sa.EEGDataStream)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
     */
    java.util.List<org.tssg.sa.EEGProtos.EEGData> 
        getDataList();
    /**
     * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
     */
    org.tssg.sa.EEGProtos.EEGData getData(int index);
    /**
     * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
     */
    java.util.List<? extends org.tssg.sa.EEGProtos.EEGDataOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
     */
    org.tssg.sa.EEGProtos.EEGDataOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.tssg.sa.EEGDataStream}
   */
  public  static final class EEGDataStream extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.tssg.sa.EEGDataStream)
      EEGDataStreamOrBuilder {
    // Use EEGDataStream.newBuilder() to construct.
    private EEGDataStream(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EEGDataStream() {
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EEGDataStream(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<org.tssg.sa.EEGProtos.EEGData>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(
                  input.readMessage(org.tssg.sa.EEGProtos.EEGData.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGDataStream_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGDataStream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tssg.sa.EEGProtos.EEGDataStream.class, org.tssg.sa.EEGProtos.EEGDataStream.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<org.tssg.sa.EEGProtos.EEGData> data_;
    /**
     * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
     */
    public java.util.List<org.tssg.sa.EEGProtos.EEGData> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
     */
    public java.util.List<? extends org.tssg.sa.EEGProtos.EEGDataOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
     */
    public org.tssg.sa.EEGProtos.EEGData getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
     */
    public org.tssg.sa.EEGProtos.EEGDataOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tssg.sa.EEGProtos.EEGDataStream)) {
        return super.equals(obj);
      }
      org.tssg.sa.EEGProtos.EEGDataStream other = (org.tssg.sa.EEGProtos.EEGDataStream) obj;

      boolean result = true;
      result = result && getDataList()
          .equals(other.getDataList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tssg.sa.EEGProtos.EEGDataStream parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tssg.sa.EEGProtos.EEGDataStream parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tssg.sa.EEGProtos.EEGDataStream parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tssg.sa.EEGProtos.EEGDataStream parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tssg.sa.EEGProtos.EEGDataStream parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tssg.sa.EEGProtos.EEGDataStream parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tssg.sa.EEGProtos.EEGDataStream parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tssg.sa.EEGProtos.EEGDataStream parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tssg.sa.EEGProtos.EEGDataStream parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tssg.sa.EEGProtos.EEGDataStream parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tssg.sa.EEGProtos.EEGDataStream prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.tssg.sa.EEGDataStream}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.tssg.sa.EEGDataStream)
        org.tssg.sa.EEGProtos.EEGDataStreamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGDataStream_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGDataStream_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tssg.sa.EEGProtos.EEGDataStream.class, org.tssg.sa.EEGProtos.EEGDataStream.Builder.class);
      }

      // Construct using org.tssg.sa.EEGProtos.EEGDataStream.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tssg.sa.EEGProtos.internal_static_org_tssg_sa_EEGDataStream_descriptor;
      }

      public org.tssg.sa.EEGProtos.EEGDataStream getDefaultInstanceForType() {
        return org.tssg.sa.EEGProtos.EEGDataStream.getDefaultInstance();
      }

      public org.tssg.sa.EEGProtos.EEGDataStream build() {
        org.tssg.sa.EEGProtos.EEGDataStream result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tssg.sa.EEGProtos.EEGDataStream buildPartial() {
        org.tssg.sa.EEGProtos.EEGDataStream result = new org.tssg.sa.EEGProtos.EEGDataStream(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tssg.sa.EEGProtos.EEGDataStream) {
          return mergeFrom((org.tssg.sa.EEGProtos.EEGDataStream)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tssg.sa.EEGProtos.EEGDataStream other) {
        if (other == org.tssg.sa.EEGProtos.EEGDataStream.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tssg.sa.EEGProtos.EEGDataStream parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tssg.sa.EEGProtos.EEGDataStream) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.tssg.sa.EEGProtos.EEGData> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<org.tssg.sa.EEGProtos.EEGData>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tssg.sa.EEGProtos.EEGData, org.tssg.sa.EEGProtos.EEGData.Builder, org.tssg.sa.EEGProtos.EEGDataOrBuilder> dataBuilder_;

      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public java.util.List<org.tssg.sa.EEGProtos.EEGData> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public org.tssg.sa.EEGProtos.EEGData getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public Builder setData(
          int index, org.tssg.sa.EEGProtos.EEGData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public Builder setData(
          int index, org.tssg.sa.EEGProtos.EEGData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public Builder addData(org.tssg.sa.EEGProtos.EEGData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public Builder addData(
          int index, org.tssg.sa.EEGProtos.EEGData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public Builder addData(
          org.tssg.sa.EEGProtos.EEGData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public Builder addData(
          int index, org.tssg.sa.EEGProtos.EEGData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends org.tssg.sa.EEGProtos.EEGData> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public org.tssg.sa.EEGProtos.EEGData.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public org.tssg.sa.EEGProtos.EEGDataOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public java.util.List<? extends org.tssg.sa.EEGProtos.EEGDataOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public org.tssg.sa.EEGProtos.EEGData.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            org.tssg.sa.EEGProtos.EEGData.getDefaultInstance());
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public org.tssg.sa.EEGProtos.EEGData.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, org.tssg.sa.EEGProtos.EEGData.getDefaultInstance());
      }
      /**
       * <code>repeated .org.tssg.sa.EEGData data = 1;</code>
       */
      public java.util.List<org.tssg.sa.EEGProtos.EEGData.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tssg.sa.EEGProtos.EEGData, org.tssg.sa.EEGProtos.EEGData.Builder, org.tssg.sa.EEGProtos.EEGDataOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.tssg.sa.EEGProtos.EEGData, org.tssg.sa.EEGProtos.EEGData.Builder, org.tssg.sa.EEGProtos.EEGDataOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.tssg.sa.EEGDataStream)
    }

    // @@protoc_insertion_point(class_scope:org.tssg.sa.EEGDataStream)
    private static final org.tssg.sa.EEGProtos.EEGDataStream DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tssg.sa.EEGProtos.EEGDataStream();
    }

    public static org.tssg.sa.EEGProtos.EEGDataStream getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EEGDataStream>
        PARSER = new com.google.protobuf.AbstractParser<EEGDataStream>() {
      public EEGDataStream parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EEGDataStream(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EEGDataStream> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EEGDataStream> getParserForType() {
      return PARSER;
    }

    public org.tssg.sa.EEGProtos.EEGDataStream getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_tssg_sa_EEGData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_tssg_sa_EEGData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_tssg_sa_EEGData_Timestamp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_tssg_sa_EEGData_Timestamp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_tssg_sa_EEGDataStream_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_tssg_sa_EEGDataStream_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017EEGProtos.proto\022\013org.tssg.sa\"\211\002\n\007EEGDa" +
      "ta\022\r\n\005email\030\001 \001(\t\0221\n\ttimestamp\030\002 \001(\0132\036.o" +
      "rg.tssg.sa.EEGData.Timestamp\022+\n\004type\030\003 \003" +
      "(\0162\035.org.tssg.sa.EEGData.DataType\022\r\n\005val" +
      "ue\030\004 \003(\002\032\013\n\tTimestamp\"s\n\010DataType\022\010\n\004EEG" +
      "1\020\000\022\010\n\004EEG2\020\001\022\010\n\004EEG3\020\002\022\010\n\004EEG4\020\003\022\014\n\010AUX" +
      "_LEFT\020\004\022\r\n\tAUX_RIGHT\020\005\022\n\n\006ACCELX\020\006\022\n\n\006AC" +
      "CELY\020\007\022\n\n\006ACCELZ\020\010\"3\n\rEEGDataStream\022\"\n\004d" +
      "ata\030\001 \003(\0132\024.org.tssg.sa.EEGDataB\013B\tEEGPr" +
      "otosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_tssg_sa_EEGData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_tssg_sa_EEGData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_tssg_sa_EEGData_descriptor,
        new java.lang.String[] { "Email", "Timestamp", "Type", "Value", });
    internal_static_org_tssg_sa_EEGData_Timestamp_descriptor =
      internal_static_org_tssg_sa_EEGData_descriptor.getNestedTypes().get(0);
    internal_static_org_tssg_sa_EEGData_Timestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_tssg_sa_EEGData_Timestamp_descriptor,
        new java.lang.String[] { });
    internal_static_org_tssg_sa_EEGDataStream_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_tssg_sa_EEGDataStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_tssg_sa_EEGDataStream_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
